### ISSUE TITLE
Support collation into OpenMapTiles VTs

### ISSUE THREAD

**Issue by fosskers** [geotrellis/vectorpipe#49]
This can be done by following [this schema](https://openmaptiles.org/schema/). Note that special considerations may have to be made regarding pyramiding, as outlined in #14 .

**Comment by jpolchlo** [comment]
This sort of thing would be possible by providing a `Pipeline` implementation that encodes the schema.  The debate is now whether we _should_ provide this by default.

**Comment by CloudNiner** [comment]
Multiple datasets are required to create this schema, including at least a few different Natural Earth datasets and osm-lakelines. It might be possible to jam all of the geometries from different datasets into one DataFrame and encode a single Pipeline, otherwise Pipeline would need to support multiple input DataFrames before tackling this. 

There's also some infrastructure around pulling and ingesting each dataset into a DataFrame that we would probably want to include for completeness sake. Given that, I would probably argue for this to _not_ be in the baseline package. It might make sense as a separate downstream one though.

**Comment by fosskers** [comment]
Is this still desired? We can close if not.
