### ISSUE TITLE
Changeset Handling

### ISSUE THREAD

**Issue by fosskers** [geotrellis/vectorpipe#9]
OSM publishes XML changesets that are to be applied overtop a full-sized planet "snapshot". What is the best way to apply these, and how often should we do it?

Thoughts:

- Release freshly ingested VT tilesets monthly, apply diffs weekly (or daily?), overwriting any affected tiles
  - PRO: Cheaper AWS bill
  - CON: Extra dev work to write the code to manage this. More complex system.
- Release freshly ingested VT tilesets weekly, in sync with OSM Planet's releases
  - PRO: Simpler code and pipeline
  - CON: Higher AWS bill

Ping: @lossyrob @echeipesh @mojodna

**Comment by mojodna** [comment]
Look for "ACID tables" to find "discussion" of diff application + compaction pros and cons in https://docs.google.com/document/d/1xuaBVOtq3w3kDpsQAqMlzy2W27fOtlfza9qtvUrHaPk/edit

That's got some of my thinking about how to handle things. Compaction (borrowing from the leveldb approach) and generation of snapshots (which are easier to work with w/o needing to select the current version of all elements) are my primary open questions on this topic.

(I think Hive/ORC ACID tables aren't the right approach due to (current) compatibility with tools other than Hive, but they point at the historical planet archive (w/ all changesets in it) as potentially being a reasonable solution.)

To facilitate diff application, OSM replication diffs (which aren't full changesets, since they're not atomic) should be pushed through Kinesis or Kafka (preferable to a straight-up message bus as it's important to be able to have captured everything, esp. since changesets can remain open for 24 hours) and augmented (similar to https://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs)

**Comment by mojodna** [comment]
Oh:

> Release freshly ingested VT tilesets weekly, in sync with OSM Planet's releases

We're planning on doing this for the ORC file weekly, so if you sit downstream from that (and are ok with the weekly cadence), this could get a bunch easier.

**Comment by lossyrob** [comment]
Would there be a query on the ORC to only gather what has changed in the week? Or would we have to do a fresh ingest?

**Comment by mojodna** [comment]
Fresh ingest as the plan stands now. Though with a historic version, a list of changed elements could be produced.

**Comment by lossyrob** [comment]
Cool. Either would be good, incremental updates would be best, although in that case I think we'd be updating from changesets less than weekly (ideally with the minutely diffs)

**Comment by mojodna** [comment]
Agreed. Your (collective) help would be extremely beneficial to figure out how to effectively do that.

**Comment by fosskers** [comment]
> minutely diffs

@lossyrob is your vision that someone could edit the original OSM data through their site, and we'd see the analogous change in a vector tile a few minutes later? This approach would be important if we're intending to become a general, live tile service. If we're not, then a weekly cadence wouldn't hurt and would yield a simpler pipeline.

**Comment by fosskers** [comment]
Superseded by the recent Planet History work.
